### PR TITLE
Create info.json

### PR DESCRIPTION
**Pull request by roma1201**

### CODE REVIEW

**Review by altbee — CHANGES_REQUESTED** [review]
Please add logo.png under the same folder. (128*128 resolution)

**Review by altbee — CHANGES_REQUESTED** [review]
Could you update the logo png?
Currently, it's in transparent bg.

Please update to:
-transparent bg
-colored circle
-your logo

OK?

**Comment by altbee** [comment]
yes

**Comment by roma1201** [comment]
check

**Review by altbee — APPROVED** [review]

**Pull request merged**
