### PR TITLE
avax/0xF45Bef5909BC38786CA4D87Bf1dC11D15503b664

### PR DESCRIPTION
**Pull request by Gunther-Schulz**

### CODE REVIEW

**Review by altbee — CHANGES_REQUESTED** [review]
Folder name should be in lowercase.
Image size should be less than 128*128

**Comment by Gunther-Schulz** [comment]
> Folder name should be in lowercase. Image size should be less than 128*128

done

**Review by altbee — CHANGES_REQUESTED** [review]
Why do you change .gitignore?
Image width and height are too big, and image content is small

**Comment by Gunther-Schulz** [comment]
> Why do you change .gitignore? Image width and height are too big, and image content is small

Fixed. Thank you for pointing it out.

**Review by altbee — APPROVED** [review]

**Pull request merged**
